# Generated by Django 2.2.11 on 2020-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='url',
            field=models.URLField(help_text='Please use the following format: https://www.jmr.pl', max_length=2000),
        ),
    ]
